### ISSUE TITLE
Other Models on Azure

### ISSUE THREAD

**Issue by xu23ai** [chuanqisun/iter#2]
Hello @chuanqisun I hope this reaches you. Thank you for such a clean , elegant solution. I am not that familiar with this language. 
I have a few questions. How can I run this on my own pc , are their any instructions or guidelines you may have?

Then how do I change the model on Azure as I am connecting to the same model. There are a few I setup like davinci or text models. Is there a way to select this or are you able to accept the entire endpoint url.

When I insert the entire url of the endpoint there is an error message. Hope you can advise, and thank you for this elegant piece of work. i like the minimalist feel

**Comment by chuanqisun** [comment]
Hey there, thanks for trying out the tool. There are different kinds of models on Azure. The older generations behave like text completion. The news generations behave like chat. `text-davinci` belongs to the older family of models which iter cannot support, because the entire UI is designed around the chat-based experience. 

Iter does not accept the full url. It only accepts the host root url and automatically detects what models are compatible. If your model is not showing up, it is possible that you haven't deployed any compatible models on Azure yet. Specifically, you need to deploy gpt-3.5 turbo and gpt-4. There might be limited access imposed by Microsoft.

Related documentation
- https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?pivots=programming-language-studio&tabs=command-line
- https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/create-resource?pivots=web-portal

**Comment by chuanqisun** [comment]
Custom model names are now supported. When adding a new endpoint, user can now input their custom deployment names (comma separated). Thank you for the feedback
